    p6: Participant;
    tenant?: string;
    configOverwrite?: IConfig;
    p5: Participant;
     * Whether to skip the prejoin button 'Join' click when joining.
     * A flag that tests can set, which signals to the framework that the (rest of the) test suite should be skipped.
     * An optional string to append to the URL when joining the room.
    /**
    /** The name of the room to join */
     **/
     * Config overwrites to pass to IParticipantJoinOptions.
     */

    times: any;
     * Test properties provided by the test file via TestProperties.setTestProperties. Used by the framework to
    /**
     */
    /** A room name automatically generated by the framework for convenience. */
    roomName: string;
     */
    iFrameApi?: boolean;
     */
    skipInMeetingChecks?: boolean;
    name: 'p1' | 'p2' | 'p3' | 'p4' | 'p5' | 'p6';

     * Whether to skip waiting for the participant to join the room. Cases like lobby where we do not succeed to join
     */
 */
     * An optional string to append to the URL when joining the room.
    configOverwrite?: IConfig;

     * a WebhooksProxy instance itself.

     * Options used when generating a token.

     */
import { IToken, ITokenOptions } from './token';
    /**
    /**
    skipPrejoinButtonClick?: boolean;
    p4: Participant;
    p3: Participant;
export type IContext = {



    /**

     */
    /**
    /**

     */
     *  ensureOneParticipant, ensureTwoParticipants, etc. from participants.ts.
    /**
     * A string value indicates the reason for the skipped (to be included in the Allure report).
export type IParticipantOptions = {
     */
     */
    /** An optional token to use. */
    /** Whether it should use the iFrame API. */
import { IConfig } from '../../react/features/base/config/configType';
    roomName: string;
     * Whether to skip in meeting checks like ice connected and send receive data. For single in meeting participant.
};
    skipWaitToJoin?: boolean;
     * set up the context appropriately.
     */
    p2: Participant;
    skipDisplayName?: boolean;
    /** Determines the browser instance to use. */

    /**
     **/
import type WebhookProxy from './WebhookProxy';
 * Options for joinConference.
    roomName?: string;
    urlAppendString?: string;
    p1: Participant;
    /**
import { ITestProperties } from './TestProperties';
    /**
    testProperties: ITestProperties;
    token?: IToken;
import type { Participant } from './Participant';
     * An optional tenant to use. If provided it overrides the default.
     * Config overwrites to use.
    /**

export type IParticipantJoinOptions = {
     */

    skipWaitToJoin?: boolean;
};
     * The skip waiting for the participant to join the room setting to pass to IParticipantJoinOptions.
    skipDisplayName?: boolean;
    /**
    /**

    /**

    /**
     *  The up-to-six browser instances provided by the framework. These can be initialized using
/**
     * Whether to skip the prejoin button 'Join' click when joining.
    skipPrejoinButtonClick?: boolean;
    webhooksProxy: WebhookProxy;

     */
    skipSuiteTests: boolean | string;
export type IJoinOptions = {
     */
    tenant?: string;


     * Note that this is only configured for roomName, if a test wishes to use a different room name it can set up
    tokenOptions?: ITokenOptions;

     * An optional tenant to use. If provided the default tenant is changed to it.
     * Whether to skip setting display name.
     *The skip display name setting to pass to IParticipantJoinOptions.
};
     * A WebhooksProxy instance generated by the framework and available for tests to use, if configured.
    /**

    urlAppendString?: string;
};

     * To be able to override the ctx generated room name. If missing the one from the context will be used.
    /**
     */
     * based on the logic of the test.
    /**
     */
     */

